export const ceg = [
  {
    section: 'Program Requirement',
    modules: [
      { code: 'CG1111', completed: true },
      { code: 'CG1112', completed: true },
      { code: 'CS1010', completed: true },
      { code: 'CS1231', completed: true },
      { code: 'MA1511', completed: true },
      { code: 'MA1512', completed: false },
      { code: 'MA1508E', completed: false },
      { code: 'CG2023', completed: true },
      { code: 'CG2027', completed: true },
      { code: 'CG2028', completed: true },
      { code: 'CG2271', completed: true },
      { code: 'CS2040C', completed: true },
      { code: 'CS2101', completed: true },
      { code: 'CS2113T', completed: true },
      { code: 'EE2026', completed: true },
      { code: 'EG2401A', completed: true },
      { code: 'ST2334', completed: true },
      { code: 'CG3207/CS3230', completed: false },
      { code: 'CP3880/EG3611A', completed: false },
      { code: 'CG4002', completed: false },
      { code: 'EE4204', completed: false },
    ],
  },
  {
    section: 'General Education',
    modules: [
      { code: 'GEQ1000', completed: true },
      { code: 'GER1000', completed: true },
      { code: 'GET1XXX', completed: false },
      { code: 'GEH1XXX', completed: true },
      { code: 'GES1XXX', completed: true },
    ],
  },
];
